import LeftMenu from "./ChatUI/LeftMenu"
import MidPart from "./ChatUI/midpart/MidPart"
import ChatBlock from "./ChatUI/chatblock/ChatBlock"
import { useState, useEffect } from "react"
import { useActiveStore } from "../store/zustand"


const databaseSchema = "create type public.continents as enum (\n  'Africa',\n  'Antarctica',\n  'Asia',\n  'Europe',\n  'Oceania',\n  'North America',\n  'South America'\n);\n create table public.countries (\nid bigint generated by default as identity primary key,\nname text,\niso2 text not null,\niso3 text,\nlocal_name text,\ncontinent continents\n);"


const ChatUI = () => {

  const [icon, setIcon] = useState(0)
  const active = useActiveStore(state => state.active)
  const icons = ['chat', 'setting', 'list', 'database']

  return (
    <div className="w-[70%] h-[85%] flex flex-row">
        <div className="w-[5%] h-full bg-gradient-to-b from-fuchsia-500 to-violet-500 flex flex-col items-center gap-[8px] pt-[5px]">
            <LeftMenu icons={icons}  icon={icon} setIcon={setIcon}/>
        </div>
        <div className="w-[25%] h-full bg-indigo-400 p-[0.5%]" >
            <MidPart icon={icon} databaseSchema = {databaseSchema}/>
        </div>
        <div className="w-[70%] h-full bg-indigo-200 flex flex-col">
            <ChatBlock key={`chat-${active}`} database = {databaseSchema}/>
        </div>
    </div>
  )
}

export default ChatUI